### ISSUE TITLE
Radar-Docker Webserver Setup

### ISSUE THREAD

**Issue by rocketsciencenerd** [RADAR-base/RADAR-Docker#203]
Hello,

I am setting up radar-docker for a project I am working on. 

I have been unable to get `mydomain.com/managementportal` working without a reverse proxy for some reason. Every time I went to my domain I got a "refused to connect" error.

I did a bit of digging and found that managementportal is running as shown:

<img width="550" alt="Screen Shot 2019-11-01 at 10 00 08 AM" src="https://user-images.githubusercontent.com/29738804/68047893-c40d5900-fcb5-11e9-9701-c1c1bd7d34eb.png">

I then setup nginx on my vm and had it re-route the management portal ip of `http:172.23.0.7:8080` to mydomain.com/managementportal and I was able to connect just fine.

The question is, why did I need to set up my own web server to re-route the managementportal ip? Did I miss something in the config? I imagine this hacky way of getting the management portal running on my domain will cause other issues (Such as email forwarding)

The following is my `.env` file:
<img width="809" alt="Screen Shot 2019-11-01 at 2 49 08 PM" src="https://user-images.githubusercontent.com/29738804/68048364-c7551480-fcb6-11e9-9067-12942b13e367.png">

I can't figure out where it is getting `http:172.23.0.7:8080` from. That IP doesn't seem to be in my `docker-compose.yml` file either? 

Thanks! 
Katie

**Comment by nivemaham** [comment]
@rocketsciencenerd Thanks for reporting the issue. Could you share your resulting `etc/webserver/nginx.config`?
This could be because of some issues with nginx.config. 
Could you try mentioning `NGINX_PROXIES=radar-base.jh.edu`?
@K1Hyve @blootsvoets Can you guys help @rocketsciencenerd with the configs?

**Comment by rocketsciencenerd** [comment]
Hi @nivemaham,

Below is the resulting nginx.conf file. 

`worker_rlimit_nofile 8192;

events {
  worker_connections  4096;  ## Default: 1024
}

http {
  default_type application/octet-stream;
  log_format   main '$remote_addr - $remote_user [$time_local]  $status '
    '"$request" $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';
  tcp_nodelay  on;

  # hide nginx version
  server_tokens off;

  # add nosniff header (https://www.owasp.org/index.php/List_of_useful_HTTP_headers)
  add_header X-Content-Type-Options nosniff;

  # For logins, make 2 requests per second at most
  limit_req_zone $binary_remote_addr zone=login_limit:10m rate=2r/s;

  server {
    listen                    80 default_server;
    listen                    [::]:80 default_server;
    server_name               radar-base.jh.edu;
    location / {
      return                    301 https://$server_name$request_uri;
    }
    location ^~ /.well-known {
      allow all;
      root  /data/letsencrypt/;
    }
  }

  server { # simple reverse-proxy
    listen                    443 ssl http2 default_server;
    listen                    [::]:443 ssl http2 default_server;
    server_name               radar-base.jh.edu;

    ssl                       on;

    add_header                Strict-Transport-Security "max-age=31536000" always;

    ssl_session_cache         shared:SSL:20m;
    ssl_session_timeout       10m;

    ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers               "ECDH+AESGCM:ECDH+AES256:ECDH+AES128:!ADH:!AECDH:!MD5;";

    ssl_stapling              on;
    ssl_stapling_verify       on;
    resolver                  8.8.8.8 8.8.4.4;

    ssl_certificate           /etc/letsencrypt/live/radar-base.jh.edu/fullchain.pem;
    ssl_certificate_key       /etc/letsencrypt/live/radar-base.jh.edu/privkey.pem;
    ssl_trusted_certificate   /etc/letsencrypt/live/radar-base.jh.edu/chain.pem;

    access_log                /var/log/nginx/access.log;
    error_log                 /var/log/nginx/error.log;

   location /kafka/ {
      include cors.conf;
      proxy_pass         http://gateway/radar-gateway/;
      proxy_set_header   Host $host;
      proxy_http_version 1.1;
      proxy_set_header   Connection "";
    }
    location ^~ /kafka/consumers {
      deny all;
    }
    location ^~ /kafka/brokers {
      deny all;
    }
    location ~* /kafka/topics/.+/partitions {
      deny all;
    }
    location /schema/ {
      limit_except GET {
        deny all;
      }
      proxy_pass         http://schema-registry-1:8081/;
      proxy_set_header   Host $host;
      proxy_http_version 1.1;
      proxy_set_header   Connection "";
    }
    location /dashboard/ {
      proxy_pass         http://dashboard:80/;
      proxy_set_header   Host $host;
    }

    location /portainer/ {
      include ip-access-control.conf;

      proxy_pass         http://portainer:9000/;
      proxy_http_version 1.1;
      proxy_set_header   Connection "";
    }
    location /portainer/api/websocket/ {
      include ip-access-control.conf;
      proxy_pass         http://portainer:9000/api/websocket/;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection "upgrade";
      proxy_http_version 1.1;
    }
    location /api/ {
      include cors.conf;
      proxy_pass         http://rest-api:8080/api/;
      proxy_set_header   Host $host;
    }
       location /managementportal/ {
      include cors.conf;
      proxy_pass         http://managementportal-app:8080/managementportal/;
      proxy_set_header   Host $host;
    }
    location /managementportal/oauth/ {
      # Allow 20 fast-following requests, like when authorizing a user.
      limit_req zone=login_limit burst=20;
      include cors.conf;
      proxy_pass         http://managementportal-app:8080/managementportal/oauth/;
      proxy_set_header   Host $host;
    }
    location /managementportal/api/meta-token/ {
      limit_req zone=login_limit;
      include cors.conf;
      proxy_pass         http://managementportal-app:8080/managementportal/api/meta-to$
      proxy_set_header   Host $host;
    }
    location /kafkamanager/{
      include ip-access-control.conf;
      auth_basic         "Kafka manager";
      auth_basic_user_file kafka-manager.htpasswd;

      proxy_pass         http://kafka-manager:9000;
      proxy_set_header   Host $host;
    }
    include optional-services.conf;
  }
}
`

I also added the `NGINX_PROXIES=radar-base.jh.edu` to my .env file and restarted the managementportal container to no avail. Is there anything in here that you can see is obviously wrong? 

Thanks!
Katie

**Comment by ajitesh18** [comment]
Hi @nivemaham,

I am also facing the same issue. I managed to run a separate container of portainer and connected it locally to get status of each container. Most of containers are running successfully except the Management portal one (with below error) -

"Connecting to localhost:8080 (127.0.0.1:8080) wget: can't connect to remote host (127.0.0.1): Connection refused"

Hi @rocketsciencenerd,

172.x.x.x seems to be IP address of Docker network that have been configured during setup.

![image](https://user-images.githubusercontent.com/34085883/68192668-03f57880-fff5-11e9-8d5c-1d0272f06574.png)

Thanks!
Ajitesh

**Comment by K1Hyve** [comment]
Hi @rocketsciencenerd, 
From what I understood the managementportal is working properly but there is an issue with Nginx. I don't exactly know what is the issue now but I can help with debugging it. 
First I would run `netstat -ntlp` to see if the Nginx is listening on port 80 and if it is then which interface it's listening on. Ideally, it should be `0.0.0.0` or the public address of your machine. You can also check this with running `curl -v localhost` and checking the result, normally you should be redirected to the https version of the site and get a `404 Not Found` message. This means the docker setup might be okay and there is a network issue.
You can check the firewall and see if it's blocking 80 and 443 port, `iptables -L -n` will give you insight on the firewall in your local machine. If you have an external firewall or load balancer you should check them as well to see if they allow access to this port. 
In the Nginx config file that you have attached, the https is enabled and maybe it's trying to redirect to port 443 on the first request. 
```
    location / {
      return                    301 https://$server_name$request_uri;
    }
```

**Comment by K1Hyve** [comment]
Hi @ajitesh18, please check the logs of the managementportal and check if there is an error mentioned in that.

**Comment by nivemaham** [comment]
> Hi @nivemaham,
> 
> Below is the resulting nginx.conf file.
> 
> [nginx_conf.txt](https://github.com/RADAR-base/RADAR-Docker/files/3807176/nginx_conf.txt)
> 
> I also added the `NGINX_PROXIES=radar-base.jh.edu` to my .env file and restarted the managementportal container to no avail. Is there anything in here that you can see is obviously wrong?
> 
> Thanks!
> Katie

Could you try running the `bin/radar-docker install` after mentioning the value for `NGINX_PROXIES`?
And yes. @K1Hyve is correct about the HTTPS enabled.

**Comment by ajitesh18** [comment]
> Hi @ajitesh18, please check the logs of the managementportal and check if there is an error mentioned in that.

Hi @K1Hyve ,

I have checked the logs of the managementportal and it seems to be stuck while starting Liquibase. 

The application will start in 10s...,
,
        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗,
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗,
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝,
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║,
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗,
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝,
,
:: JHipster 🤓  :: Running Spring Boot 1.5.9.RELEASE ::,
:: http://jhipster.github.io ::,
,
2019-11-06 01:26:22.295  INFO 1 --- [           main] o.r.management.ManagementPortalApp       : The following profiles are active: prod,swagger,
2019-11-06 01:26:29.044 DEBUG 1 --- [           main] i.g.j.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase synchronously,
---------------------------------------------------------------------------------------------------------------

Also the last output from the container displayed the same error as @rocketsciencenerd mentioned (Connection refused) -

![image](https://user-images.githubusercontent.com/34085883/68260702-1ae1ac80-0081-11ea-8de9-a22b93984c23.png)

Kindly let me know if I need to share any logs / configuration file.

Thanks.
Ajitesh

**Comment by nivemaham** [comment]
@ajitesh18 If managementPortal is stuck while starting liquibase, it is a different problem. It looks like the system did not exit properly which made it impossible to remove the lock from Liquibase. There is a way to remove this lock manually by login into the database.

**Comment by rocketsciencenerd** [comment]
Hi @nivemaham and @ajitesh18 I found the solution. After looking at the nginx logs I found this:

`nginx: [emerg] host not found in upstream "radar-integration" in /etc/nginx/optional-services.conf:3
2019/11/13 13:51:54 [emerg] 1#1: host not found in upstream "radar-integration" in /etc/nginx/optional-services.conf:3`

I navigated to the `optional-services.conf` file commented everything out, and restarted the nginx container. The managementportal works fine now! Hope this helps others.

**Comment by nivemaham** [comment]
@rocketsciencenerd Do you get this issue even though when you use the commands with `bin/radar-docker` ?
@ajitesh18 Have a look at this stack over flow [question](https://stackoverflow.com/questions/15528795/liquibase-lock-reasons) on how to release the liquibase lock

**Comment by rocketsciencenerd** [comment]
@nivemahm what command should I be using? I used the radar-docker install command and radar-log command to try and figure out what was happening. Is there another command that would be helpful in this instance?

**Comment by rocketsciencenerd** [comment]
@nivemaham I am now having the database lock issue as well. How do I run the `UPDATE DATABASECHANGELOGLOCK SET LOCKED=FALSE, LOCKGRANTED=null, LOCKEDBY=null where ID=1;` command on the liquibase database? I'm not sure how to access it through managementportal. Thanks!

**Comment by ajitesh18** [comment]
Hi @rocketsciencenerd , thank you for providing the command to check logs. There is no optional-services config file for me in nginx container and management portal exited for me with an error stating "[emerg] 1#1: host not found in upstream "managementportal-app" in /etc/nginx/nginx.conf:113
nginx: [emerg] host not found in upstream "managementportal-app" in /etc/nginx/nginx.conf:113".

It keeps on exiting with this error along with gateway error. Could you please help?

@nivemaham 
I am also stuck at the same issue. Opened postgresql container and tried to execute the command but it failed stating "databasechangelog relation does not exist". I am sure I am not executing the command at the right location, so it would be helpful, if you can let us know how to remove database lock. 

Thanks!

**Comment by yatharthranjan** [comment]
Hi guys,

You will probably need to use the database first and then run the command like this -

```
docker-compose exec radarbase-postgresql /bin/sh
/ # psql -U radarbase restsourceauthorizer 
restsourceauthorizer=# \dt
                 List of relations
 Schema |         Name          | Type  |   Owner   
--------+-----------------------+-------+-----------
 public | databasechangelog     | table | radarbase
 public | databasechangeloglock | table | radarbase
 public | rest_source_user      | table | radarbase
(3 rows)
```
Now you can run the query.

**Comment by yatharthranjan** [comment]
Also for an easy fix. If there is no important data in postgres (as I think you guys are just installing for the first time), then you can also stop the postgres service and delete everything in the postgres directory and restart the postgres service. That should fix this issue but you will lose any data in postgres.

**Comment by ajitesh18** [comment]
Hi @yatharthranjan ,

Thank you for providing the fix. Deleting everything in the postgres directory worked fine to bypass the lock issue. Restarted management portal and it started successfully.

![image](https://user-images.githubusercontent.com/34085883/69019881-ef9e7c00-09f5-11ea-8971-3fc02a54b580.png)

However, I am still facing issue with nginx that resulted in 502 Bad Gateway error. Keep on restarting as you can see from the screen-shot and when I have looked into the logs, it seems not able to find host in upstream "managementportal-app"

![image](https://user-images.githubusercontent.com/34085883/69019988-5c197b00-09f6-11ea-9f81-51aefc448a74.png)

Please let me know if you have any suggestions to fix this nginx issue. Thanks!

**Comment by rocketsciencenerd** [comment]
@ajitesh18 check out what I did to fix your current issue above. I had to comment out the lines in that optional-services.conf file in the webserver directory in RADAR-Docker, save it and restart the Nginx docker container to get things running.

**Comment by ajitesh18** [comment]
Thanks @rocketsciencenerd . It worked for me as well. However, there is some other issue regarding certificate that is now causing nginx to restart. Registered domain is not able to fetch a certificate from "Letsencrypt" due the same 502 Bad Gateway error. I will try to get the certificate manually and will provide an update.

Really appreciate the quick response and support. Thanks again!

**Comment by ajitesh18** [comment]
Struggling to fix this Bad Gateway error. Posting the screen-shot to get some help, may be someone have encountered the same issue while generating certificates -

![image](https://user-images.githubusercontent.com/34085883/69032587-3a34ee00-0a20-11ea-9d7f-673a0d685310.png)

Any help would be much appreciated. Thank you!

**Comment by rocketsciencenerd** [comment]
@ajitesh18 I am using a ssl cert from my organization so I replaced the following lines in the nginx.conf file:
`  ssl_certificate                /etc/letsencrypt/live/radar-base.jh.edu/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/radar-base.jh.edu/privkey.pem;
    ssl_trusted_certificate   /etc/letsencrypt/live/radar-base.jh.edu/chain.pem;
`
with my certs: 

`    ssl_certificate              ssl/MY_CERT.cer;
      ssl_certificate_key      ssl/MY_PRIVATE_KEY.key;
      ssl_dhparam                ssl/dhparam.pem;
`
Might help you out if you have that option?

**Comment by ajitesh18** [comment]
Thanks @rocketsciencenerd . I have managed to install the certificates manually for the registered domain, restarted Nginx but still not able to run it. It keeps on restarting stating that there is no file exist for fullchain.pem when there is a file present at the location -

![image](https://user-images.githubusercontent.com/34085883/69108882-5d5fac00-0ab9-11ea-835d-170bc9225c36.png)

Am I missing something here? Do I need to specify anything in configuration file?

**Comment by rocketsciencenerd** [comment]
Hi @ajitesh18 I had to generate my own .pem file. I just did some googling and found this site: 

https://askubuntu.com/questions/644020/how-to-generate-openssl-pem-file-and-where-we-have-to-place-it

Should help!

**Comment by ajitesh18** [comment]
Thank you @rocketsciencenerd for all the help! Locally I am able to access the management portal and Nginx is also working fine.

![image](https://user-images.githubusercontent.com/34085883/69116953-7ffdbf00-0ad1-11ea-9a6c-d4f0e07bec34.png)

For SSL, I will generate my own .pem file and place it accordingly as per the shared link. Thanks again!
